from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(827, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(249, 20, 1161, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())

        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMouseTracking(True)

        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(50, 800, 113, 32))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(10, 440, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.label_Set_Param = QtWidgets.QLabel(self.centralwidget)
        self.label_Set_Param.setGeometry(QtCore.QRect(20, 20, 221, 111))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_Set_Param.setFont(font)
        self.label_Set_Param.setObjectName("label_Set_Param")
        self.label_Pulse = QtWidgets.QLabel(self.centralwidget)
        self.label_Pulse.setGeometry(QtCore.QRect(20, 130, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Pulse.setFont(font)
        self.label_Pulse.setObjectName("label_Pulse")
        self.label_Time_wait = QtWidgets.QLabel(self.centralwidget)
        self.label_Time_wait.setGeometry(QtCore.QRect(10, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Time_wait.setFont(font)
        self.label_Time_wait.setObjectName("label_Time_wait")
        self.pushButton_Confirm1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Confirm1.setGeometry(QtCore.QRect(130, 180, 111, 31))
        self.pushButton_Confirm1.setObjectName("pushButton_Confirm1")
        self.pushButton_Confirm2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Confirm2.setGeometry(QtCore.QRect(130, 320, 111, 31))
        self.pushButton_Confirm2.setObjectName("pushButton_Confirm2")
        self.lineEdit_pulse = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pulse.setGeometry(QtCore.QRect(10, 180, 111, 31))
        self.lineEdit_pulse.setObjectName("lineEdit_pulse")
        self.lineEdit_time = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time.setGeometry(QtCore.QRect(10, 320, 113, 31))
        self.lineEdit_time.setObjectName("lineEdit_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 24))
        self.menubar.setObjectName("menubar")
        self.menuOpengl = QtWidgets.QMenu(self.menubar)
        self.menuOpengl.setObjectName("menuOpengl")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOpengl.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_Confirm1.clicked.connect(self.pushButton_Confirm1.click)
        self.pushButton_Confirm1.clicked.connect(self.frame.setFocus)
        self.pushButton_Confirm2.clicked.connect(self.frame.setFocus)
        self.pushButton_Start.clicked.connect(self.lineEdit_time.copy)
        self.pushButton_Start.clicked.connect(self.lineEdit_pulse.copy)
        self.pushButton_quit.clicked.connect(MainWindow.close)
        self.pushButton_Start.clicked.connect(self.frame.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_quit.setText(_translate("MainWindow", "Quit"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start!"))
        self.label_Set_Param.setText(_translate("MainWindow", "Set Parametrs to\n"
" Start modeling!"))
        self.label_Pulse.setText(_translate("MainWindow", "PULSE:"))
        self.label_Time_wait.setText(_translate("MainWindow", "Time wait:"))
        self.pushButton_Confirm1.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_Confirm2.setText(_translate("MainWindow", "Confirm"))
        self.menuOpengl.setTitle(_translate("MainWindow", "Opengl"))
